### ISSUE TITLE
The final masks have shifted

### ISSUE THREAD

**Issue by Cyrus1993** [sabarim/STEm-Seg#22]
Hi, I ran this project in the test phase in Windows. The outputs look right, but the masks have been moved. What is the cause of this phenomenon?
sample output:
https://drive.google.com/file/d/1YpT7fpVOjL5s-0SIC79Hzf_vGDj7VLNr/view?usp=sharing
https://drive.google.com/file/d/1YmLauDdqKJ6KyZkHIPsL5MP6IXK3E569/view?usp=sharing

**Comment by Ali2500** [comment]
Is it always the same amount of shift with every video? It's possible some part of the code is behaving differently on Windows. You'll probably have to debug the inference code more to find out where the error is happening (i.e. is the issue already there in the network's output, or is it something that happens when the masks are resized, padded etc.)

**Comment by Cyrus1993** [comment]
Thanks for your reply.
Yes, the displacement rate seems to be the same. The main problem seems to be in the pycocotools library. There are no problems with Linux.
Thank you so much

**Comment by sabarim** [comment]
Closing due to lack of further activity
